title: NetBioMed 2025
#> # this means to ignore newlines until "baseurl:"
description: The official website for NetBioMed satellite
baseurl: "" # the subpath of your site, e.g. /blog
url: "netbiomed-symposium.github.io/NetBioMed2025/" # the base hostname & protocol for your site
# Build settings
markdown: kramdown


logo: "../css/img/official_logo.png"

social: 
  name: Official Twitter account
  link: "https://x.com/netbiomed2025"
  name: Official Bluesky account
  link: "https://bsky.app/profile/netbiomed2025.bsky.social"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://x.com/netbiomed2025
  - title: bluesky
    url: https://bsky.app/profile/netbiomed2025.bsky.social

# Build settings
markdown: kramdown
permalink: pretty
